### ISSUE TITLE
 NamePoolData pattern failed

### ISSUE THREAD

**Issue by zhang1201234** [MJx0/AndUE4Dumper#3]
I : Game: com.xd.TLglobal
I : Process ID: 31245
I : Output directory: /sdcard/Download
I : Dump Library: false
I : Full: true
I : Headers: true
I : Objects: false
I : Script: true
I : ==========================
I : Reading Target UE4 Library Info...
I : ei_class: 64
I : e_machine: 0xb7
I : Library: /data/app/~~UXEkJHWA2jD_Oot5CIAWwg==/com.xd.TLglobal-RFxr36NfoY94v0BYBRZ9Cg==/lib/arm64/libUE4.so
I : BaseAddress: 0x72fbe44000
I : ==========================
I : Initializing Game Profile...
E : NamePoolData pattern failed.
I : Dump Status: DS_ERROR_INIT_NAMEPOOL
I : Dump Location: /sdcard/Download/UE4Dump3r/com.xd.TLglobal

what can i do ？

**Comment by MJx0** [comment]
make a pattern to NamePoolData and GUObjectArray in IDA or just use hardcoded addresses
