### ISSUE TITLE
com.pubg.imobile [arm64 ] gname ptr decryption failed

### ISSUE THREAD

**Issue by Poko-Apps** [MJx0/AndUE4Dumper#6]
As the title suggests dumper exits with error msg **UE_DS_ERROR_INIT_GNAMES**, after looking into the gname ptr decryption function in IDA pro it seems your code have a lil mistake . Here's how i corrected it and it worked properly in latest version of the Game (2.8.0 - 64bit) .

![img1](https://github.com/MJx0/AndUE4Dumper/assets/97328832/55b483a8-108c-47e7-95c8-d06ac219efb0)

Hope you update the source soon :)

**Comment by MJx0** [comment]
Thanks for pointing this out. I had it right before but it looks like i messed up that part with the recent changes ):
I uploaded a new update.
